#!/bin/bash
clear
dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
cd $dir
export PATH=$HOME/.gem/ruby/2.6.0/bin:$PATH
sudo ps -ef | grep "jekyll" | grep -v grep |awk '{print $2}' | xargs sudo kill -9
sudo jekyll serve --watch
